language: c
script: asdf plugin-test trdsql https://github.com/johnlayton/leesroad.git 'kind -version' --asdf-tool-version 0.5.1
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
